spring:
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/downloader}
    username: ${JDBC_USERNAME:postgres}
    password: ${JDBC_PASSWORD:postgres}
  liquibase:
    change-log: db/changelog/main-changelog.xml

image:
  directory: ${IMAGE_SAVE_DIRECTORY:cats/}
  maxCount: ${IMAGE_DOWNLOAD_MAX_COUNT:-1}